source 'https://rubygems.org'

ruby '2.6.3'

gem 'activesupport'
gem 'acts_as_list'
gem 'administrate'
gem 'administrate-field-carrierwave'
gem 'administrate-field-image'
gem 'aws-sdk-rails'
gem 'aws-sdk-rds', '~> 1'
gem 'aws-sdk-s3', '~> 1'
gem 'aws-sdk-ses', '~> 1'
gem 'bcrypt'
gem 'bootstrap', '~> 4'
gem 'carrierwave'
gem 'carrierwave-base64'
gem 'chunky_png'
gem 'coffee-rails'
gem 'date_validator'
gem 'dotenv-rails'
gem 'faker'
gem 'fog-aws'
gem 'iso_country_codes'
gem 'jbuilder'
gem 'jquery-rails'
gem 'mini_magick'
gem 'mini_racer'
gem 'passenger'
gem 'pg'
gem 'phonelib'
gem 'puma'
gem 'rails', '~> 5'
gem 'sassc'
gem 'turbolinks'
gem 'uglifier'
gem 'pry-rails'
gem 'rb-readline'

group :development, :test do
  gem 'listen'
  gem 'rspec-rails'
end
